VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
Vagrant.configure(VAGRANTFILE_API_VERSION) do | config|
	config.vm.define "centos6-1" do |centos1|
		centos1.vm.box = "centos/6"
		centos1.vm.hostname = "centos1"
		centos1.vm.network "public_network", ip: "192.168.1.220"
	end 
	config.vm.define "centos6-2" do |centos2|
		centos2.vm.box = "centos/6"
		centos2.vm.hostname = "centos2"
		centos2.vm.network "public_network", ip: "192.168.1.221"
	end
end
