Vagrant.configure(2) do |config|
  config.vm.box = "opentable/win-2012r2-standard-amd64-nocm"
   config.vm.provider "virtualbox" do |vb|
	vb.gui = true
	vb.memory = "1024"
	vb.name = "win2012R2"
   end
end
