Vagrant.configure(2) do |config|
  config.vm.box = "freebsd/FreeBSD-11.0-RC2"
  config.vm.box_check_update = false
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end
end
