# Multi-machine Vagrantfile build - March 18,2016
# Provider: Digital Ocean specific

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'digital_ocean'
Vagrant.configure(2) do |config|
  config.vm.box = "digital_ocean"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # config.ssh.insert_key = "false"
  config.ssh.private_key_path = '/home/oss/.ssh/keys/id_rsa'
    config.vm.provider :digital_ocean do |provider|
    	provider.token = '6cbdb1572816b5bfab6c07309e9772ad4e030fb7df361e051ca744fa49cfc819'
    	provider.image = 'ubuntu-14-04-x64'
    	provider.region = 'nyc2'
    	provider.size = '512mb'
    end

    config.vm.define "lbsrv001" do |lb_config|
      lb_config.vm.hostname = '/home/oss/automation/ansible/playbooks/lbsrv-001.opensitesolutions.com'
    end

    config.vm.define "websrv001" do |websrv001_config|
      websrv001_config.vm.hostname = 'websrv-001.opensitesolutions.com'
      # websrv001_config.vm.synced_folder "/home/oss/repos/web/fixyourip.com","/var/www/html/"
      websrv001_config.vm.provision "ansible" do |ansible|
        ansible.playbook = "/home/oss/repos/vagrant/ansible-playbooks/websrv-playbook.yml"
      end
    end

    config.vm.define "websrv002" do |websrv002_config|
      websrv002_config.vm.hostname = 'websrv-002.opensitesolutions.com'
      websrv002_config.vm.synced_folder "/home/oss/repos/web/fixyourip.com","/var/www/html/"
      websrv002_config.vm.provision "ansible" do |ansible|
        ansible.playbook = "/home/oss/repos/vagrant/ansible-playbooks/websrv-playbook.yml"
      end
    end

    config.vm.define "dbsrv001" do |dbsrv001_config|
      dbsrv001_config.vm.hostname = 'dbsrv-001.opensitesolutions.com'
      dbsrv001_config.vm.provision "ansible" do |ansible|
        ansible.playbook = "/home/oss/repos/vagrant/ansible-playbooks/dbsrv-playbook.yml"
      end
    end

    config.vm.define "dockersrv001" do |dockersrv001_config|
      dockersrv001_config.vm.hostname = 'dockersrv-001.opensitesolutions.com'
      dockersrv001_config.vm.provision "ansible" do |ansible|
        ansible.playbook = "/home/oss/repos/vagrant/ansible-playbooks/dockersrv-playbook.yml"
      end
    end

    config.vm.define "vagrantsrv001" do |vagrantsrv001_config|
      vagrantsrv001_config.vm.hostname = 'vagrantsrv-001.opensitesolutions.com'
      vagrantsrv001_config.vm.provision "ansible" do |ansible|
        ansible.playbook = "/home/oss/repos/vagrant/ansible-playbooks/vagrantsrv-playbook.yml"
      end
    end

    config.vm.define "devsrv001" do |devsrv001_config|
      #devsrv001_config.vm.synced_folder "/home/oss/automation/vagrant-env/","/vagrant"
      devsrv001_config.vm.hostname = "devsrv-001.opensitesolutions.com"
      devsrv001_config.vm.provision "ansible" do |ansible|
        ansible.playbook = "/home/oss/repos/vagrant/ansible-playbooks/devsrv-playbook.yml"
        # ansible.playbook = "users.yml"
      end
    end
end
