Vagrant.configure('2') do |config|

  config.vm.provider :linode do |provider, override|
    override.ssh.private_key_path = '~/.ssh/id_rsa'
    #override.vm.box = 'linode/ubuntu1404'
    #override.vm.box_url = "https://github.com/displague/vagrant-linode/raw/master/box/linode.box"
    config.vm.box = 'linode/ubuntu1404'

    provider.api_key = ''
    provider.distribution = 'Ubuntu 14.04'
    provider.datacenter = 'fremont'
    provider.plan = 'Linode 1024'
    #provider.planid = 1
    # provider.planid = <int>
    # provider.paymentterm = <*1*,12,24>
    # provider.datacenterid = <int>
    # provider.image = <string>
    # provider.imageid = <int>
    # provider.kernel = <string>
    # provider.kernelid = <int>
    # provider.private_networking = <boolean>
    # provider.stackscript = <string> # Not Supported Yet
    # provider.stackscriptid = <int> # Not Supported Yet
    # provider.distributionid = <int>

    # Shell Scripts
    config.vm.provision :shell, path: "setup.sh"
    config.vm.provision :shell, path: "apache.sh"
  end
end
