Vagrant.configure(2) do |config|
  config.vm.box = "opentable/win-2012-standard-amd64-nocm"
  config.vm.box_check_update = false
  config.vm.hostname = "win2012-r2"
  config.vm.box_check_update = false
  config.vm.network "private_network",ip:"192.168.33.11"
   config.vm.provider "virtualbox" do |vb|
     vb.gui = true # false, does  not display the gui
     vb.memory = "1024"
     vb.name = "win2012-r2"
   end
end
