Vagrant.configure(2) do |config|
  config.vm.box = "box-cutter/ubuntu1404-desktop"
  config.vm.synced_folder "/home/oss/Documents", "/vagrant"
  config.vm.provider "virtualbox" do |vb|
	vb.memory = "512"
	vb.name = "ubuntu-desktop14.04"
  end
end
