Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_url = "https://atlas.hashicorp.com/centos/boxes/7"
   	config.vm.provider "virtualbox" do |vb|
   	config.vm.network "public_network",bridge:'wlan0'
     	vb.gui = true
     	vb.memory = "512"
   end
end
