---
- hosts: all
  tasks:
    - name: Download and install Jenkins REPO key
      shell: wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
    - name: Add Jenkins Repository entry to Source list
      shell: echo "deb http://pkg.jenkins-ci.org/debian binary/" >> /etc/apt/sources.list

    - name: Update Packages
      apt: update_cache=yes

    - name: Installing Development Applications
      apt:  pkg={{ item }}
      with_items:
          - curl
          - git
          - golang
          - gccgo-go
          - python-pip
          - ansible
          - puppet-common
          - sshpass
          - sysstat

      #- name: Downloading latest stable docker
      #get_url: url=https://get.docker.com dest=/tmp/docker-install.sh validate_certs=yes
      #shell: curl -fsSL https://get.docker.com/ | sh
    #- name: Install Docker
    #  shell: sh /tmp/docker-install.sh
    - name: Downloading vagrant version 1.8.1
      shell: curl -L https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb >> /tmp/vagrant.deb
    - name: Install Vagrant 1.8.1
      apt: deb=/tmp/vagrant.deb

    - name: Install Jenkins
      apt:  pkg=jenkins state=latest
