---
- hosts:  all
  tasks:
    - name: Update Packages
      apt: update_cache=yes

    - name: Install Application Packages
      apt:  pkg={{ item }}
      with_items:
          - curl
          - mysql-server

    - include: ansible/task/users.yml
