---
- hosts:  all
  tasks:
    - name: Update Packages
      apt: update_cache=yes

    - name: Install Application Packages
      apt:  pkg={{ item }}
      with_items:
          - git
          - curl
          - vagrant
          - python-pip
