---
- hosts: all 
  become: yes
  become_user: vagrant
  tasks:
    - name: Update Packages
      yum: update_cache=yes

    - name: Install Application Packages
      yum:  pkg={{ item }}
      with_items:
          - curl
          - git
          - vagrant
          - gccgo-go
          - python-pip
