---
  - hosts: www
    remote_user: vagrant
    sudo: yes
    pre_tasks:
      shell: echo ' Beginning to configure web server..'
    roles:
      - nginx
        post_tasks:
          shell: echo 'Done configuring nginx web server...'
